### ISSUE TITLE
Allow append to current playlist; from the browser screen

### ISSUE THREAD

**Issue by boxerfan88** [xbmc/chorus2#131]
At the browser screen, when browsing through folders, one can add the folder to the current playlist.
Request for enhancement to be able to **append** the folder to the current playlist.

![kodi_chorus_browser_enh](https://cloud.githubusercontent.com/assets/23348797/20123885/587e3d0a-a65d-11e6-81de-813867946c25.jpg)

**Comment by PROF-FART** [comment]
Just wanted to add that this would be amazing for people like me who have music folders that are too crazy to allow Kodi to "library" them and too lazy to clean terabytes of metadata by hand. I just use the Kodi file browser for all my music. 

Also, I believe this would allow me to build playlists in Google Music EXP and other music addons, which seem to work otherwise very well in Chorus2 file browser.

My main goal for Chorus2 is to run Kodi headless and load up hours of music without having to turn the TV on.

**Comment by jez500** [comment]
On the roadmap, have recently added for files just need to extend it to folders too, stay tuned!

**Comment by jez500** [comment]
Added to 2.4.0
