### ISSUE TITLE
Things from 'Browser' will only play in Kodi and not Locally

### ISSUE THREAD

**Issue by Drsela** [xbmc/chorus2#174]
If you click the Browser top in the left menu, browse to a music folder and choose a music file (mp3, whatever) it will only play in Kodi.

**Comment by jez500** [comment]
This might be possible but would be limited to files only (not addons)

**Comment by floreo** [comment]
Hello,

since it's closed also in #237 I'm answering here just to know if it would be possible to have this feature ?
I'm guessing the project is not much active but the interface is really cool and it would be a really awesome feature, to be able to play Kodi's playlists (or music) within the local queue. Concerning addons it's not that important since it's not brought by Kodi directly.
Thanks and great job !

**Comment by malard** [comment]
closing, but anyone is welcome to submit a PR
