### ISSUE TITLE
Moving (currently playing) track in Kodi playlist inserts track again instead of moving it

### ISSUE THREAD

**Issue by kopf** [xbmc/chorus2#196]
Steps to reproduce:

* Play an album on Kodi via chorus2
* Move the currently playing track to somewhere else in the playlist (I moved it up in the playlist when I observed this behaviour)
* Instead of being moved up, the currently playing track stays where it is, but the same track is inserted at the position it should've been moved to

**Comment by jez500** [comment]
For this one I think I am going to just disable the ability to move the currently playing track, pretty sure that is the way Chorus1 worked. 

The issue is: to move an item in the playlist, it has to be removed and then re-added in the new position, that causes issues if that item is currently playing. I have spent near on 2h on this now (attempting a stop, remove, insert, resume) and still can't get it going. It is such an edge case that It is not worth any more time. 

So you will just have to shuffle items around what is playing, sorry :)

**Comment by kopf** [comment]
Grand! To be honest, it sounds like this is something that should be part of the actual Kodi API - a `moveToPlaylistPosition` RPC call or something. Would it be an idea to ping the core devs here or should a ticket be opened? (or is having an RPC call for it a terrible idea?)

**Comment by jez500** [comment]
In 2.4.0 you can no longer move the playing item. You'll have to move the items around it.

The api has `playlist.swap` which is intended for switching the position of 2 items, that is ok for moving an item up or down by one position but not great for moving an item to a completely new pos. Would be nice for the api to have that functionality but i have a long list of higher priority api improvements so if you really want it, then I'll let you bug the devs ;)
