### ISSUE TITLE
Development process

### ISSUE THREAD

**Issue by mehdilauters** [xbmc/chorus2#238]
Hi,
I follow the development process until running grunt, but then I am not able to connect to any urls:

````
[BS] Proxying: http://192.168.0.92:8080
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3102
    External: http://192.168.1.32:3102
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.32:3001
````
The 3102 and 8080 port connections stay pending, the 3001 one gives me BrowserSync (but I don't really know what to do with it).

Is this behavior normal? Can you update the Readme or answer here how to get the chorus interface to be ready to develop?

**Comment by jez500** [comment]
Hi!

If you want to use browser sync, you might need to update the proxy IPs in the gruntfile (something I have been meaning to make more generic for a while) in my environment `192.168.0.92:8080` is the pc running kodi and should be able to access that directly. In your example `192.168.1.32` should be the pc running grunt (dev env) so it is proxying `192.168.0.92` to `192.168.1.32` and would visit `192.168.1.32:3001` to see `192.168.0.92:8080`.

You would only need browsersync if you are doing lots of css updates (as it live refreshes) otherwise simply clicking refresh does the same thing as grunt will still build the css/js/etc. 

Lastly I have the `dist` folder from this repo symlinked to to Kodis `addons/webinterface.default.dev` folder

Hopefully that makes a bit of sense, I should make a more comprehensive guide, but you are the first to ask about this :)

**Comment by jez500** [comment]
Any luck @mehdilauters ?

**Comment by mehdilauters** [comment]
I didn't had time to check it but thanks for your answer I will try it soon!

**Comment by mehdilauters** [comment]
That's working! Thank you
