### ISSUE TITLE
Sound reset each songs & subtittles 

### ISSUE THREAD

**Issue by drizzik** [xbmc/chorus2#254]
Hey, 

Your work on this web interface is awesome but I have some issues. 
The first one is that when I'm listening music on my second computer, the volume is reset every song.
And is it possible to add something to change audio/subtitle in the HTML 5 player ?

Thank you anyway for your work

**Comment by jez500** [comment]
Hi! Glad you like it

Volume issue fixed in 2.4.4 which will roll out with the next Kodi release

Subtitles in the html5 player is a no-go unfortunately, I have looked into it a couple of times and is far too complex as the browser doesn't support `srt` files. Maybe in the future if Kodi supports transcoding they could be 'burnt' into the video.
