### ISSUE TITLE
 webinterface.default.2.X.X.zip not there

### ISSUE THREAD

**Issue by allefeld** [xbmc/chorus2#443]
### Describe the bug

The README refers to "`webinterface.default.2.X.X.zip` from the releases page", but on that page there is no such file. I figured out that I had to download the complete zip there and then rezip the `dist` folder.

**Comment by malard** [comment]
closing as this is a lack of understanding from the poster, the X.X denotes a replacement for the actual number

**Comment by allefeld** [comment]
Did you even check before assuming my "lack of understanding"?

The last version is 2.4.8, therefore (obviously) the instruction is to download `webinterface.default.2.4.8.zip`.

On the releases page linked to, <https://github.com/xbmc/chorus2/releases>, under Version 19.x-2.4.8 there are two files for download, one of which is a zip file. However, it is listed as "Source code (zip)" and is downloaded as `chorus2-19.x-2.4.8.zip` which does not conform to the pattern `webinterface.default.2.X.X.zip`.

If one ignores this inconsistency and tries to use it for installation, it doesn't work. What does work is to unzip the file `chorus2-19.x-2.4.8.zip`, zip only the contained folder `dist`, and then install from that file.

For other releases there is a third file, but the name is `webinterface.default.19.x-2.4.7.zip`, which also doesn't conform to the pattern  `webinterface.default.2.X.X.zip`, but it's easy to figure out.

**Comment by malard** [comment]
Your initial ticket was so vague you are asking my to be pscyhic to understand the intent of your report. The clarification is better, when the readme was originally written the naming convention was in one way, since it was last updated the naming convention has changed. This addon has not been heavily maintained in some years. It is getting a bit of love now and will be cleaned up. That said as this package exists in the official repo the readme file will be updated to explain how to get it more easily and remove the manual installation steps.

Thanks
