### ISSUE TITLE
Search is broken v2.0.10

### ISSUE THREAD

**Issue by un1versal** [xbmc/chorus2#73]
1) Searching for something automatically searches in all categories, cant be stopped

2) if you search for something that doesnt exist, the search just keeps going for what seem forever. half hour later still going, 1 hour later going for gold, 2 hours later I realized this is very likely also broken.

Bug one is new, the other not.

**Comment by jez500** [comment]
I have been thinking about this a bit, but not completely sure which way I want to attack it. 

Ideas:

* When you are in the "context" of a media type, eg. "movies" and you do a search it only searches that type. Maybe have a button that says search all?
* Add a "cancel search" button
* While searching, the media types are links so you could click on say... "movies" and it would cease searching for anything else
* I have also noticed the infinite search thing, not sure exactly what causes it but most of the time if you just search again (or refresh) it works, will take a bit of tracking down
*  I am halfway through adding the ability for addon modules to tap into the search so it can search addon endpoints. eg. Radio stations, soundcloud (similar to Chorus 1)

Any feedback or ideas to make it better is welcome. I would like to sort out search in one hit.

Because search is the best! Kinda wish it was more prominent in Kodi itself

**Comment by un1versal** [comment]
What immediately occurs to me is::

When you are in a specific category and search you only search that category +

if you are not then you could have a all,movies,music,addon filter type somewhere near search bar perhaps.

Since this is suppose to be the next official web interface it makes sense to me that the strings and consistency match kodi, since I done this for kodi I dont mind doing it here since I use this.

**Comment by jez500** [comment]
Fixed in 2.3.8, sorry you didn't get to see it mate
